[workspace]
members = [
    "rust_learn",
    "hello_macro_derive",
     ]


[profile.release]
incremental = true
debug = 1               # only line info
opt-level = 3           # code optimization


[profile.dev]
opt-level = 0


[patch.'crates-io']
