[package]
name = "rust_learn"
version = "0.1.0"
authors = ["alanding <395577197@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
hello_macro_derive = { path = "../hello_macro_derive" }
